# Generated by Django 5.2.13 on 2026-04-29 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_code', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('location', models.CharField(max_length=160)),
                ('priority', models.CharField(choices=[('high-priority', 'High'), ('medium-priority', 'Medium'), ('low-priority', 'Low')], default='medium-priority', max_length=20)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
